### ISSUE TITLE
How does this work with electron?

### ISSUE THREAD

**Issue by marcvdm** [egoist/vbuild#1]
I just installed vbuild with the starter kit for electron.

i ran ```vbuild --electron --watch -e main.js``` and also tries ```vbuild --electron --dev -e main.js``` but its not really doing anything other than compiling.

Am i doing this wrong or is there a beter way?

**Comment by egoist** [comment]
Currently you can run:

```bash
# entry should be vue app entry, not electron's
$ vbuild -e app.js --electron --watch
```

And then open a new terminal tab:

```bash
$ electron main.js
```

If you have better idea to use Vue with Electron, please let me know!

**Comment by egoist** [comment]
Currently you can run:

```bash
# entry should be vue app entry, not electron's
$ vbuild -e app.js --electron --dev
```

update main.js to:

```js
...
if (process.env.NODE_ENV === 'development') {
  mainWindow.loadURL('http://localhost:4000/index.html');
} else {
  mainWindow.loadURL('file://' + __dirname + '/index.html');
}
...
```

And then open a new terminal tab:

```bash
$ NODE_ENV=development electron main.js
```

If you have better idea to use Vue with Electron, please let me know!

**Comment by egoist** [comment]
Fix:

We shouldn't modify main.js to: `mainWindow.loadURL('http://localhost:4000/index.html')`, since in this way we are not able to use native node functions in rendered process, like `require('github')`, because it's a remote url.

Instead, load an `index.dev.html` from file system:

index.dev.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>App</title>
  </head>
  <body>
    <app></app>
    <script src="http://localhost:4000/assets/bundle.js"></script>
  </body>
</html>
```
