### ISSUE TITLE
Unit Test support ?

### ISSUE THREAD

**Issue by throrin19** [egoist/vbuild#104]
Hi,

Where is the support of the unit tests within vbuild? For example with mocha + chai + avoriaz?

**Comment by egoist** [comment]
Hi there, it's a bit different to work with vbuild now, vbuild 6 is totally refactor for good reasons.

For unit testing, you can check out https://github.com/egoist/vbuild#custom-build-process

This [vue-cli-karma](https://github.com/egoist/vue-cli-karma/blob/master/index.js) module is made for `vue-cli`'s `vue build` command, but it works here too.
