### ISSUE TITLE
Including karma in vbuild core

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#109]
If you want to see that `vbuild test` comes out of the box, please add reaction `+1` to this comment, otherwise add `-1` reaction.

Pros:

- Out of the box, requires no config to run karma with mocha and jasmine. Currently you can use [vue-cli-karma](https://github.com/egoist/vue-cli-karma) module with [`run` function](https://github.com/egoist/vbuild#custom-build-process) to achieve the same thing.

Cons:

- 4 more dependencies

**Comment by zephraph** [comment]
I think if it's relatively easy to set up then just documenting the process would suffice. Vbuild is a bit hefty as is.

**Comment by egoist** [comment]
Now [running karma is easy as 1 2 3](https://github.com/egoist/vbuild-karma), so closed 🤣
