### ISSUE TITLE
Maintain support for the current LTS version

### ISSUE THREAD

**Issue by throrin19** [egoist/vbuild#110]
Hi,

It's possible to make the node engine compatible with node >= 6 ? The v6 is the current LTS and it's used in many structures. 

In my company, we used only the LTS versions of NodeJS.

Thanks

**Comment by egoist** [comment]
Sounds reasonable, upgrading to `v6.3.0` should fix this. Tested against node v6.9.2 and it works fine.

**Comment by throrin19** [comment]
Thanks :+1:
