### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#112]
I'd like to provide some basic support for Vue SSR in `vbuild serve` command

**Comment by egoist** [comment]
I'll wait for Vue `2.2` to be released.

**Comment by egoist** [comment]
Closed since this needs a big refactor in vbuild (which mean we need to run two webpack config to run the `vbuild serve` command), might implement as another tool since now we can use `vbuild` [as a node.js module](https://github.com/egoist/vbuild#javascript-api), for simple use case of SSR,[ this will be enough](https://github.com/egoist/vbuild/blob/master/docs/recipes/cjs-and-umd-format.md#server-bundle).

**Comment by Anonyfox** [comment]
could you provide a really idiot-proof example of how to generate a server bundle from a vanilla vbuild project (with vue-router and vuex) and how to use it from within express.js? 

I know this is a more general topic, but you seem to have very excellent knowledge about the vue ecosystem, so a definite guide would be awesome!

**Comment by egoist** [comment]
@Anonyfox it would be similar to https://github.com/vuejs/vue-hackernews-2.0 I will convert that project to a vbuild-based project later tomorrow 🙂

**Comment by Anonyfox** [comment]
awesome! :)

**Comment by marshauf** [comment]
Any news regarding this topic?

**Comment by egoist** [comment]
@marshauf I might do this when Vue 2.2 is released, since it will have better ssr support and this is more complicated than I thought 🤗

**Comment by egoist** [comment]
Oh, btw, [nuxt.js](https://github.com/nuxt/nuxt.js) could generate static website too.

**Comment by Aduril** [comment]
Hey,

I would love to do ssr, too. What's the status?

**Comment by Anonyfox** [comment]
Yes, in my mind it makes total sense for vbuild to not only generate the client-side bundle, but also the server-side bundle in on pass (if configured?). 

Seems that Vue 2.2 is now out, too @egoist :)

**Comment by marshauf** [comment]
I got vbuild to generate a server bundle but when I run the code in the server npm tries to execute .vue files as JavaScript files and throws a SyntaxError. It seems like the vue components are not rendered correctly. Any ideas?

I am following these guides:
https://github.com/egoist/vbuild/blob/master/docs/recipes/cjs-and-umd-format.md#server-bundle
https://vuejs.org/v2/guide/ssr.html

**Comment by egoist** [comment]
Maybe this is what you want https://github.com/egoist/unvue
