### ISSUE TITLE
Shorthand for setting env

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#115]
eg: `vbuild --env.BABEL_ENV test` will set `process.env.BABEL_ENV` to `test`

p.s. do you think automatically loading `.env` file is useful?

**Comment by cj** [comment]
@egoist yes :) I do this right now https://gist.github.com/ebcc7038e5eee6a1f315687840c7e8d5.  you could just add an `envs` option to automatically do it. i.e.

```
export default {
  envs: ['FB_API_KEY']
}
```

**Comment by egoist** [comment]
@cj I guess we can load .env and automatically set them in DefinePlugin.

**Comment by egoist** [comment]
Landed in `v6.9.0` 

https://github.com/egoist/vbuild#load-env-variables
