### ISSUE TITLE
Entry file index.js does not exist

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#116]
After doing a fresh `vbuild init` calling `vbuild --dev` only prints the following error anf exits:
`vbuild · Entry file index.js does not exist, did you forget to create one?`

But when calling `npm run dev` everything seems to be fine, except that **hot reloading** does not seem to be present out of the box...

**Comment by egoist** [comment]
You should call `vbuild -c` instead, it uses `vbuild.config.js`

**Comment by boustanihani** [comment]
Thanks
