### ISSUE TITLE
hot-/live-reloading broken in cloud IDE

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#119]
I am calling `vbuild -c --dev` to start my dev server. All works fine. When I change a `.vue` file vbuild recompiles but I see no changes in my browser windows unless I do a refresh manually?

Isn't `vbuild -c --dev` supposed to do some hot-/live-reloading?

**Comment by egoist** [comment]
Is there any output in the browser console? You're supposed to see something like:

<img width="825" alt="2017-02-17 2 44 27" src="https://cloud.githubusercontent.com/assets/8784712/23035719/101ec21c-f4bb-11e6-9866-30db35be61b6.png">

Or can you provide the steps to reproduce this?

If you see something like: `Root or manually mounted instance modified. Full reload required.` that might be a bug in vbuild.

**Comment by boustanihani** [comment]
I am getting:

`EventSource cannot load http://0.0.0.0:8080/__webpack_hmr. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx.c9users.io' is therefore not allowed access.`

**Comment by boustanihani** [comment]
I am using Cloud9, this is how my `vbuild.config.js` looks like:

```javascript
module.exports = (options, req) => ({

  host: '0.0.0.0',
  port: 8080,

  entry: 'src/index.js',
  dist: 'dist',
  html: {
    title: 'vbt'
  },
  postcss: [
    req('autoprefixer')({
      browsers: ['ie > 8', 'last 4 versions']
    })
  ],
  webpack(cfg) {
    cfg.resolve.modules.push(path.resolve('src'))

    return cfg
  }
})
```

**Comment by egoist** [comment]
hmm no sure about this, works fine on my local machine.

**Comment by boustanihani** [comment]
For reproduction you may simply try using vbuild with https://c9.io/, they offer free accounts...

**Comment by boustanihani** [comment]
I just upgraded to the latest version and everything seems to be working fine

**Comment by egoist** [comment]
Just noticed [this](https://github.com/facebookincubator/create-react-app/blob/master/CONTRIBUTING.md#heuristics) in create-react-app, maybe it's related to this issue

**Comment by boustanihani** [comment]
Just upgraded to the latest vbuild and the issue seems to be back again :(

**Comment by egoist** [comment]
Try `v6.24.12`, it's most likely because in the client-side, webpack-hot-middleware can't connect to `0.0.0.0`

**Comment by boustanihani** [comment]
Cool its working again :+1:
