### ISSUE TITLE
vbuild self-update notice?

### ISSUE THREAD

**Issue by Anonyfox** [egoist/vbuild#120]
It seems that with the current activity and progress, it would be nice to automatically console.log a tiny notice if the currently used version of vbuild is out-of-date somehow, right when you use it. Just an idea, since I just noticed huge improvements over the last days alone, reading this now out of pure luck today.

**Comment by egoist** [comment]
hmm weird, we already did that https://github.com/egoist/vbuild/blob/master/bin/vbuild#L7

**Comment by Anonyfox** [comment]
you're the man. really. closing this as solved with a big: thanks!
