### ISSUE TITLE
Error using --config without filename

### ISSUE THREAD

**Issue by kincaidoneil** [egoist/vbuild#122]
Using the latest version of vbuild, when I run an NPM script with `vbuild index.js --config`, which per the documentation, should automatically use `vbuild.config.js`, it throws an error: `Module build failed: TypeError: Path must be a string. Received true`.

*However*, if I run a script with `vbuild index.js --config vbuild.config.js`, it compiles fine. (In both instances, I have the config file at the root directory).

I believe it's an issue with CSS extraction per the call stack; if I remove the style element from my component file, the error goes away.

I have a pretty barebones repo to demonstrate the issue [here](https://github.com/kincaidoneil/testing).

- Node v7.5.0
- vbuild 6.11.0
- Mac OS 10.12.3

Is there anything trivial I'm doing wrong or is this just a bug?

Thanks for the great tool!

**Comment by egoist** [comment]
This bug is due to `vue-loader` will always load postcss config from `--config` argument, and it cannot be a boolean `true`, https://github.com/vuejs/vue-loader/pull/653

**Comment by egoist** [comment]
The current workaround is using the alias `-c` to set config file.

**Comment by egoist** [comment]
https://github.com/vuejs/vue-loader/pull/653 this is merged, it will be fixed once they publish a new version.

**Comment by egoist** [comment]
`vue-loader@11.1.0` is there, you can reinstall `vbuild` to receive updates!
