### ISSUE TITLE
UNMET PEER DEPENDENCY html-webpack-plugin@2.28.0

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#123]
When installing latest vbuild (vbuild@6.12.0) there is an unmet dependency =>

`UNMET PEER DEPENDENCY html-webpack-plugin@2.28.0`

And when calling `vbuild -c --dev` we get =>

```
ERROR in /home/ubuntu/workspace/~/vbuild/lib/dev-client.es6
Module not found: Error: Can't resolve 'eventsource-polyfill' in '/home/ubuntu/workspace/node_modules/vbuild/lib'
 @ /home/ubuntu/workspace/~/vbuild/lib/dev-client.es6 1:0-31
 @ multi /home/ubuntu/workspace/~/vbuild/lib/dev-client.es6 src/index.js

 ERROR  Compiling failed!
```

**Comment by egoist** [comment]
It works all good for me, any repro?

**Comment by boustanihani** [comment]
could you try deleting the node_modules folder and installing a clean vbuild ?

**Comment by egoist** [comment]
I checked it by running in a `docker run -it -p 4000:4000 --rm node /bin/bash` instance and it's working fine

**Comment by boustanihani** [comment]
Okay I found out why. I needed to call `npm install` manually because I deleted the `node_modules` folder.

But I thought vbuild will install all dependencies automatically when calling `vbuild -c --dev` ?

**Comment by egoist** [comment]
Hmm, what dependencies are supposed to be installed?

**Comment by boustanihani** [comment]
The `"devDependencies": { "vbuild": "^6.0.0"  }`. They where missing because I deleted the `node_modules` folder inside my project directory.

**Comment by egoist** [comment]
If you installed vbuild in your project, use that if possible, sometimes some module version will mismatch if you mixed global and local vbuild.

btw if you're using Yarn, there's a shorthand to run `./node_modules/.bin/vbuild` : `yarn vbuild`

**Comment by boustanihani** [comment]
thanks

**Comment by boustanihani** [comment]
By the way, I didn't manually  install `vbuild` in my project. First I installed `vbuild` **globally** and then I used `vbuild init` to initialize my project and it installed `vbuild` under `node_modules` because `vbuild` is listed under `devDependencies`.

**Comment by egoist** [comment]
Yep, then you can run vbuild with npm scripts.
