### ISSUE TITLE
entry parameter from vbuild.config.js not being taken

### ISSUE THREAD

**Issue by sylvainpolletvillard** [egoist/vbuild#129]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

![image](https://cloud.githubusercontent.com/assets/566536/23235121/92979780-f954-11e6-9230-5e5ac71e386b.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?** I changed the entry file in `vbuild.config.js` but it still throws an error asking for an `index.js` file. I should be able to change the name of the entry file.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, vbuild version and Operating System.**
latest vbuild on Windows 10

**Comment by egoist** [comment]
Did you run `vbuild -c`?

**Comment by sylvainpolletvillard** [comment]
No, I run  `vbuild --dev` for dev mode and `vbuild` for production. 

It worked with this `-c` attribute. Is is the same than `--config` ? I thought it was used to specify a custom path for the config file ?

**Comment by egoist** [comment]
Yep, you can see all CLI aliases by running `vbuild -h`

**Comment by sylvainpolletvillard** [comment]
Note that this is also a confusing point for a newcomer, since this is a different behaviour than other tools that use a configuration file (webpack.config.js, postcss.config.js, .babelrc etc...). When a vbuild.config.js file exists, I think vbuild should use it by default just like Webpack & PostCSS. I thought this `config` argument was only meant to change the path to the config file

**Comment by egoist** [comment]
Done in `v6.17.1`
