### ISSUE TITLE
Error when starting vbuild after version change (6.11.0 => 6.22.0)

### ISSUE THREAD

**Issue by alekbarszczewski** [egoist/vbuild#137]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When starting vbuild@6.22.0 with command `vbuild --config --dev` it throws error:

```
TypeError: Path must be a string. Received true
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/alekbarszczewski/vbuild-bug

**What is the expected behavior?**

It should not throw error (it works after downgrading to vbuild@6.11.0).

**Please mention other relevant information such as the browser version, Node.js version, vbuild version and Operating System.**

* Node v6.3.0
* Vbuild v6.22.0
* OS X 10.11

**Comment by egoist** [comment]
Fixed in `v6.22.1`

**Comment by egoist** [comment]
btw, you can also use `yarn vbuild` to run `./node_modules/.bin/vbuild`, eg: `yarn vbuild -- --dev`

**Comment by alekbarszczewski** [comment]
Thanks!
