### ISSUE TITLE
Question: create-vue-app vs vbuild init

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#141]
Are there any differences between `create-vue-app` & `vbuild init` ?

What is the preferred way to start a project if only vbuild will be used?

**Comment by egoist** [comment]
`vbuild init` no longer exists. You can even make a vue-cli template that uses vbuild.

**Comment by boustanihani** [comment]
Ah okay so we should use `create-vue-app` right ?

The vbuild API is changing very frequently :)

**Comment by egoist** [comment]
I guess there're no breaking changes in core API ☺️, and `create-vue-app` is a successor of `vbuild init` which focuses on Vue.js app only.

**Comment by boustanihani** [comment]
Thanks for your feedback :bowtie:
