### ISSUE TITLE
Unexpected token in vue files

### ISSUE THREAD

**Issue by RX14** [egoist/vbuild#142]
I just upgraded vbuild, and now i'm getting the following error in my vue files:
```
ERROR in ./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Index.vue
Module parse failed: /data/college/2016-17/computing/coursework/code/frontend/node_modules/vue-loader/lib/selector.js?type=script&index=0!/data/college/2016-17/computing/coursework/code/frontend/src/views/Index.vue Unexpected token (19:4)
You may need an appropriate loader to handle this file type.
|   },
|   computed: {
|     ...mapState(["passes"]),
|     futurePasses() {
|       let now = moment()
 @ ./src/views/Index.vue 3:2-90
 @ ./src/router.js
 @ ./src/app.js
 @ multi /home/rx14/.config/yarn/global/~/vbuild/lib/dev-client.es6 src/app.js
```

This seems like a bug because this `.vue` file used to compile before I upgraded. As far as I know ES6 is still supported by default in vue files.

Gist of vue file: https://gist.github.com/9ee85ddfe4a88fc8babb09f11cb1110a
Gist of vbuild config: https://gist.github.com/4b291d2ca711dbf79a91752419701322

I also made a minimal git repo which reproduces the error: https://github.com/RX14/vbuild-error-reproduce
```
$ node --version
v6.1.0
```

```
$ vbuild --version
6.24.1
```

**Comment by egoist** [comment]
Hmm.. I can't repro the bug with the repo you provide.. Can you ensure no custom babel config was used?

**Comment by egoist** [comment]
The only warning I got is: 

```bash
WARNING in ./src/App.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/egoist/dev/temp/vbuild-error-reproduce/node_modules/babel-loader/lib/index.js!/Users/egoist/dev/temp/vbuild-error-reproduce/src/App.js
    Used by 2 module(s), i. e.
    /Users/egoist/dev/temp/vbuild-error-reproduce/node_modules/babel-loader/lib/index.js!/Users/egoist/dev/temp/vbuild-error-reproduce/src/app.js
* /Users/egoist/dev/temp/vbuild-error-reproduce/node_modules/babel-loader/lib/index.js!/Users/egoist/dev/temp/vbuild-error-reproduce/src/app.js
    Used by 1 module(s), i. e.
    /Users/egoist/dev/temp/vbuild-error-reproduce/node_modules/babel-loader/lib/index.js!/Users/egoist/dev/temp/vbuild-error-reproduce/index.js
```

**Comment by RX14** [comment]
I've never written a `.babelrc` in my life, so I don't think it's that. `locate` tells me that the only `.babelrc` files are inside `node_modules`. I'm not sure why it works on your PC at all. I'm using archlinux if that helps.

Perhaps these warnings when installing `vbuild` are related?
```
$ yarn global add vbuild
yarn global v0.21.3
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "babel-load-config@0.1.0" has unmet peer dependency "babel-core@^6.23.1".
warning "eslint-loader@1.6.3" has unmet peer dependency "eslint@>=1.6.0 <4.0.0".
warning "babel-loader@6.4.0" has unmet peer dependency "babel-core@^6.0.0".
warning "babel-loader@6.4.0" has unmet peer dependency "webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc".
warning "extract-text-webpack-plugin@2.1.0" has unmet peer dependency "webpack@^2.2.0".
warning "eslint-config-vue-app@1.2.0" has unmet peer dependency "eslint@^3.15.0".
warning "url-loader@0.5.8" has unmet peer dependency "file-loader@*".
warning "html-webpack-plugin@2.28.0" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc".
warning "webpack-dev-middleware@1.10.1" has unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
warning "vue-loader@11.1.4" has unmet peer dependency "css-loader@*".
warning "vue-loader@11.1.4" has unmet peer dependency "vue-template-compiler@^2.0.0".
warning "eslint-config-xo@0.17.0" has unmet peer dependency "eslint@>=3.6.0".
warning "eslint-plugin-vue@2.0.1" has unmet peer dependency "eslint@^2.0.0 || ^3.0.0".
warning "eslint-plugin-react@6.10.0" has unmet peer dependency "eslint@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
success Installed "vbuild@6.24.1" with binaries:
      - vbuild
warning No license field
Done in 7.81s.
```

**Comment by egoist** [comment]
If you're using external `.babelrc` the cli logs will tell you like this:

```bash
$ vbuild
> Using external babel configuration
> location: "~/dev/temp/xxx/.babelrc"
```

I don't think the warnings are related to this, it's a known Yarn issue for checking peerDependencies too early.

---

I tested it on a fresh docker(ubuntu) instance again, everything works fine.

**Comment by RX14** [comment]
@egoist Definitely don't get that message here. Hmm, I wonder what could be going on.

**Comment by egoist** [comment]
Oh, you don't need this https://github.com/RX14/vbuild-error-reproduce/blob/master/package.json#L12

`yarn remove vue-loader` and retry and it should work.

**Comment by egoist** [comment]
Figured:

You have `vue-loader` installed locally in your project, so the vue-loader looks for babel-loader in current directory to transpile `script` tag while you don't have that loader there.

**Comment by RX14** [comment]
Thanks!

Just by-the-way, is there any way to get vbuild to not clear the screen when starting up?

**Comment by egoist** [comment]
currently no, it's for better readability, why you want to disable that?

**Comment by RX14** [comment]
@egoist There are some things logged before the screen is cleared that quickly go away, after the screen is cleared you can't read them. Plus it means you can't scroll up and see your previous command's output.

**Comment by marshauf** [comment]
@egoist Also the percentage/cleaning the screen pollutes log files when you build bundles with build servers.
