### ISSUE TITLE
video (poster="xxx.png") url loader is not work

### ISSUE THREAD

**Issue by zhuowenli** [egoist/vbuild#143]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

```
<template lang="pug">
    .tutorials
        video(controls poster="../assets/poster.png") ❌
            source(src="../assets/video.mp4" type="video/mp4")
        img(src="../assets/poster.png") ✔️
</template>
```

**Please mention other relevant information such as the browser version, Node.js version, vbuild version and Operating System.**

- node: v6.9.1
- vue: v2.1.5
- vbuild: v6.6.0

**Comment by egoist** [comment]
this doesn't seem to be a bug, vue-loader doesn't support this, you may post it as a feature request to vuejs/vue-loader

check out http://vue-loader.vuejs.org/en/configurations/asset-url.html
