### ISSUE TITLE
Pug now has to be installed globally

### ISSUE THREAD

**Issue by RX14** [egoist/vbuild#144]
When trying to use pug templates (`<template lang="pug">`), before upgrading vbuild (from 4.x.x I think) I could install pug in the project's package.json and it would pick it up and use that version. Now I need to `yarn global add pug` to get my project to compile. Is there any reason for this change?

```
$ vbuild --version
6.24.7
$ node --version
v6.1.0
```

**Comment by egoist** [comment]
you're probably using a global installed `vbuild`, this way `vue-loader` isn't installed in current working directory while your `pug` dependency is, the solution is to install vbuild locally `yarn add vbuild --dev`
