### ISSUE TITLE
Integrate Typescript support - Feature

### ISSUE THREAD

**Issue by cHolzberger** [egoist/vbuild#151]
I wonder how it is possible to add Typescript (ts-loader) to my build? Maybe its possible to turn it on and off via a flag in package.json?

**Comment by egoist** [comment]
There're two ways of adding extra loaders:

1. directly mutate webpack config:

```js
module.exports = {
  webpack(config) {
    config.module.rules.push({
      test: /\.tsx?$/,
      loader: 'ts-loader',
      options: {}
    })
    return config
  }
}
```

2. Using [webpack-chain](https://github.com/mozilla-rpweb/webpack-chain)

```js
module.exports = {
  extendWebpack(config) {
    config.module.rule('ts')
      .test(/\.tsx?$/)
      .use('ts')
        .loader('ts-loader')
        .options({})
  }
}
```

**Comment by egoist** [comment]
Here's a simple preset for typescript support, basically it just adds the ts-loader: https://github.com/egoist/vbuild/tree/master/packages/vbuild-preset-typescript
