### ISSUE TITLE
It not work when using 'vbuild dev --template-compiler' command

### ISSUE THREAD

**Issue by qqcome110** [egoist/vbuild#152]
```
vbuild version
$ v7.0.7
```
**vue-router** is used in my project, when I change my code:

```
import Vue from 'vue/dist/vue.common'
```
that successful 👏

so the optional `--template-compiler` is not always work with me when I switch multi versions (vbuild)

**Comment by qqcome110** [comment]
I try!, but It not working!

**Comment by egoist** [comment]
Please provide a repo or gist with detail steps to reproduce it, it works for me though.
