### ISSUE TITLE
Use relative path for script tags after build

### ISSUE THREAD

**Issue by sylvainpolletvillard** [egoist/vbuild#153]
**Do you want to request a *feature* or report a *bug*?** feature I guess

**What is the current behavior?**
After build for production, script tags in index.html use absolute path to retrieve JS bundles:
```
<script type="text/javascript" src="/manifest.63d0fd9e.js"></script><script type="text/javascript" src="/vendor.a78ef024.js"></script><script type="text/javascript" src="/client.b866e404.js"></script>
```
**What is the expected behavior?**

A relative path for the scripts: 
```
<script type="text/javascript" src="./manifest.63d0fd9e.js"></script><script type="text/javascript" src="./vendor.a78ef024.js"></script><script type="text/javascript" src="./client.b866e404.js"></script>
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

This prevents from using the application from a **sub-path**, i.e. mywebsite.com/mysubproject/

**Please mention other relevant information such as the browser version, Node.js version, vbuild version and Operating System.**

latest vbuild, latest Node

**Comment by egoist** [comment]
Hmm, it would not work if you use history mode in router

**Comment by sylvainpolletvillard** [comment]
Is it possible to get a working history router with the app in a sub-path of the domain ?

**Comment by egoist** [comment]
The only way I can think of is using absolution path or full url including domain 😆

**Comment by sylvainpolletvillard** [comment]
Hum... I don't use the router in my application so I don't have any trouble by manually changing the paths in my `dist/index.html`

**Comment by egoist** [comment]
In fact, just set `homepage` in `package.json` or in vbuild config and you're all set https://vbuild.js.org/#/options?id=homepage

**Comment by sylvainpolletvillard** [comment]
Hum, okay, it's not perfect since I can't use the same package for different environments, but it would do the trick for now.

**Comment by egoist** [comment]
What do you mean by `same package for different environments`? You can set it in `pkg.vbuild.homepage` or using an external config file if you like.

**Comment by sylvainpolletvillard** [comment]
I work with Docker images that can be used in different environments, for example a mutualized testing environnement (`testing-repository.mycompany.com/myproject/`), then a production environment (`myproject.com`). The best practice is to keep the same Docker image in all the environments, to ensure that what has been tested is exactly what is going to production. Having a different vbuild config between the environments implies that my images will be specific to the environment. So it requires a build for each environment, which can introduce regressions or unexpected behaviour if something goes wrong during the build (different versions of the NPM dependencies for example).

Currently it's not a big deal because I have only one environment, but later I will need to configure a proxy or a middleware as a workaround.
