### ISSUE TITLE
Option to prevent terminal.clear()

### ISSUE THREAD

**Issue by apeace** [egoist/vbuild#155]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When running `vbuild`, the `\x1Bc` character is written to stdout, causing the terminal to clear. This does not apply to `vbuild dev`.

**If the current behavior is a bug, please provide the steps to reproduce.**

It is not a bug.

**What is the expected behavior?**

It would be great to be able to disable this somewhere in the options.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I have a monolithic repo which contains several different apps. When we deploy, we run a script which builds all the apps in parallel. It is annoying when `vbuild` clears the terminal, causing me to have to scroll up to see logs coming from my other builds.

**Please mention other relevant information such as the browser version, Node.js version, vbuild version and Operating System.**

vbuild 7.1.1
node 7.9.0
npm 4.2.0
OS X

**Comment by egoist** [comment]
In `v7.2` you can disable it by `--no-clear` or set `clear: false` in config file.

**Comment by apeace** [comment]
Thank you so much!
