### ISSUE TITLE
start-up template

### ISSUE THREAD

**Issue by yegor-sytnyk** [egoist/vbuild#18]
would be nice to have start-up template with a sample of custom HTML+CSS+JS, it can be created as a command of vbuild (like vbuild init) or as a template in vuejs-templates

Similar to create-react-app project

It is not obvious what should be in custom html template, how to bundle CSS and include static assets

**Comment by egoist** [comment]
Thanks for suggestion, I might make a vue-cli template today.

**Comment by egoist** [comment]
Before publishing a template, I'd like to explain about:

- custom html template: it's a just an [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md) template, which uses ejs syntax by default
- css is using postcss, with autoprefixer and postcss-nested by default, see [options](https://egoist.gitbooks.io/vbuild-handbook/content/options.html) here
- static files, just include them directly (via css, img src or import/require), file-loader will handle that for you.
