### ISSUE TITLE
JS URI is not correct in the HTML

### ISSUE THREAD

**Issue by icebob** [egoist/vbuild#2]
If I open the generated html, it won't work because the JS url started with '/'.

HTML opened from disk:` file:///D:/Work/vue-form-generator/dist/index.html`
But browser want to load js from: 
`file:///D:/assets/bundle.cc2a07533dc5e3026dc8.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

Because the url in the html is: `/assets/bundle.cc2a07533dc5e3026dc8.js`

**Comment by egoist** [comment]
You should use a simple http server to serve the html, like [serve](https://www.npmjs.com/package/serve)

Or if you want the deploy the bundled app to some address like `http://your-name.com/app-name` (i mean a subdirectory), you can just change the `publicPath` in webpackConfig for production use.

**vbuild.js**:

```js
export default {
  webpack(config, options) {
    if (!options.dev) {
      config.output.publicPath = './assets/'
    }
  }
}
```

**Comment by icebob** [comment]
Thanks!
