### ISSUE TITLE
yarn error on Win platform

### ISSUE THREAD

**Issue by yegor-sytnyk** [egoist/vbuild#26]
not sure if that should be vbuild issue

yarn keeps exiting with an error "cannot find @sindresorhus\df\index.js"
npm works fine

detailed log:

yarn install v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
[3/4] Linking dependencies...
error ENOENT: no such file or directory, open 'D:\Projects\vue-bootstrap-ui\node_modules\@sindresorhus\df\index.js'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by egoist** [comment]
what's command you ran?

**Comment by egoist** [comment]
seems it's yarn install, it cannot find `vue-bootstrap-ui\node_modules\@sindresorhus\df\index.js` so I guess it's not a vbuild issue, probably yarn

**Comment by yegor-sytnyk** [comment]
yes, yarn install

directory is missing, guess it is because that module is not working for Win, but npm is ok with that

switch back to npm for now

**Comment by egoist** [comment]
Good to know 😄, you can open an issue in Yarn's repo, I'm closing this.
