### ISSUE TITLE
vbuild.js is doesn't load by default

### ISSUE THREAD

**Issue by jgog** [egoist/vbuild#4]
This works `vbuild --dev -c vbuild.js` while this doesn't `vbuild --dev`

**Comment by egoist** [comment]
Yes, but it's not a bug.

`vbuild` without `-c` does not load `./vbuild.js`
`vbuild -c` load `./vbuild.js`
`vbuild -c xxx.js` loads any file

**Comment by jgog** [comment]
Can't we have `./vbuild.js` loaded if it exists? similar to how webpack uses `webpack.config.js`

**Comment by egoist** [comment]
Sure, I used [rollup](https://github.com/rollup/rollup) a lot when I was writing this tool, so it performs like the way rollup does. Maybe it's just inappropriate here.

You're welcome to do a PR 🤗

**Comment by egoist** [comment]
You can use https://github.com/sindresorhus/path-exists since it supports Promise.
