### ISSUE TITLE
vendor.js hash changes on every build

### ISSUE THREAD

**Issue by markschultz** [egoist/vbuild#45]
vbuild 3.1.3

1. generate initial project from default template
2. run vbuild
`dist/vendor.11172a5f.js`
3. make small change to `App.vue`
4. run vbuild
`dist/vendor.50964e69.js`

shouldn't the vendor file stay the same between builds? from what I understand we add the hash for cache purposes which is undermined if the hash changes every build.

**Comment by egoist** [comment]
Seems it's caused by webpack manifest. Fixed by add CommonsChunkPlugin for it.

**Comment by egoist** [comment]
<img width="1155" alt="2016-11-02 1 02 51" src="https://cloud.githubusercontent.com/assets/8784712/19917282/bc92f3b4-a0fc-11e6-816e-4066d452a194.png">

I just figures this out by looking at the diff, stupid but efficient 😂
