### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by marvinroger** [egoist/vbuild#46]
I feel pretty dumb to ask that, but how do we add a `favicon.ico`?

**Comment by egoist** [comment]
maybe copy-webpack-plugin?

**Comment by marvinroger** [comment]
So, with `--merge-config`? Sounds fine, if you think this should not be a "native" feature.

**Comment by egoist** [comment]
It could be a native feature though, auto copy `favicon.ico` in root directory to `dist` after running    `vbuild`.

These's also An alternative, update your npm script to:

```json
{
  "build": "vbuild && cp favicon.icon dist/"
}
```

**Comment by egoist** [comment]
I think I will add this feature later 😄

**Comment by egoist** [comment]
I would suggest vbuild to respect the `./static` folder, if it exists then copy its contents recursively into './dist' folder, how do you think?

**Comment by marvinroger** [comment]
That's how I would have done it, so I would say yes, definitely. 😉

**Comment by egoist** [comment]
Nice, `v4.0.0` ships this feature. https://vbuild.js.org/docs/static-files-like-favicon.html
