### ISSUE TITLE
Better electron support

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#50]
Currently the workflow is:

**in dev mode:**

- create an electron entry js file
- create an index.html and load it in electron entry file, the index.html would include:
```html
<script src="http://localhost:4000/client.js"></script>
```
- run `vbuild --dev --electron` for your web app
- run `electron /your/entry/file.js` for your electron app

**in production mode:**

- create an electron entry js file (same as above)
- load `./dist/index.html` in electron entry file
- run `vbuild` to build your web app to `./dist`
- package the electron app and done

---

I'm finding a way to simplify this.

**Comment by egoist** [comment]
First I will add an options `--electron` to the `vbuild init` command.

**Comment by jancel** [comment]
electron didn't work out of box... may want to add #ymmv to that option.

**Comment by RyanZim** [comment]
Any updates on this?

**Comment by egoist** [comment]
Do you still have trouble configuring vbuild for Electron app? let me know if you need help.

**Comment by jancel** [comment]
I ditched it as far as Electron was concerned.

**Comment by egoist** [comment]
You can checkout the default template generated by `vbuild init app --electron`
