### ISSUE TITLE
Use relative path to client.js

### ISSUE THREAD

**Issue by neves** [egoist/vbuild#51]
The default script tag generated in dev is:
`<script src=http://localhost:4000/client.js></script>`
But that doesn't work when accessing from my phone, for example.
How can I convert to:
`<script src=/client.js></script>`

**Comment by egoist** [comment]
I think I can add a `--host` options for this

**Comment by egoist** [comment]
Now you can use `--host you.ip` to establish the dev server, also there's a `devServer` option for advanced `webpack-dev-server` [configuration](https://webpack.github.io/docs/webpack-dev-server.html#api), eg:

```js
module.exports = {
  devServer: {
    proxy: {
      '/api': 'http://api.endpoint.com/pathname'
    }
  }
}
```

**Comment by neves** [comment]
Thanks @egoist, but I'm not sure one option would be enough.
Now I have to use --host 192.168.0.10 to work, but that's a problem cause the local ip changes.
What should be changed is this:
`<script src=http://localhost:4000/client.js></script>`
into this:
`<script src=/client.js></script>`
but now, it is:
`<script src=http://192.168.0.10:4000/client.js></script>`

**Comment by egoist** [comment]
so won't `http://192.168.0.10:4000/client.js` work for you?

**Comment by egoist** [comment]
I guess you mean change to `/client.js` is a better solution than using `--host` option

**Comment by neves** [comment]
vbuild already binds to 0.0.0.0, which is great, cause I can test from other devices, that's why relative path to client.js would makes more sense.

**Comment by egoist** [comment]
Updated, now it's served from `/`

**Comment by neves** [comment]
That's great!

**Comment by egoist** [comment]
Oh, I guess we still need to use full path like `http://host:port` when developing an Electron app
