### ISSUE TITLE
Using sass for style lang in single component throwing error

### ISSUE THREAD

**Issue by hitautodestruct** [egoist/vbuild#54]
I am trying to use the lang attribute in my style declaration for `scss`.

I installed `node-sass` and `sass-loader` I added the loader to `mergeConfig` like so:

```
module.exports = {
  title: 'myapp',
  resolve: true,
  live: true,
  mergeConfig: {
    // following options will be merged
    module: {
      loaders: [
        {
          test: /\.scss$/,
          loaders: ["sass"]
        }
      ]
    }
  }
}
```

But I'm getting an error:

```
Module not found: Error: Can't resolve 'scss' in '.../src/components/'
@ ./src/components/Input.vue 5:0-166
```

My vue file style declaration looks like this:

```
...

<style lang="scss">
$prime-color: blue;

.input { color: $prime-color; }
</style>
```

**Comment by egoist** [comment]
1. If you use sass in single file component you won't need to add loaders in webpack config, simply install the dependencies is enough
2. it should be `lang="sass"`

**Comment by egoist** [comment]
btw, why do you need `live: true`? I guess it will be live reloaded automatically if `hot reload` failed.

**Comment by hitautodestruct** [comment]
@egoist Sometimes hot reload tends to be sticky in certain use cases I have. So I use live reload 😄 

I found my issue, I was using scss instead of sass, that was what's causing the error.

Thanks, it's working now

**Comment by jazoom** [comment]
I had the same confusing issue. I have been using `lang=scss` because that is the only thing that works for SCSS with the official vue-cli webpack template. `lang=sass` only works for SASS. Perhaps this should be changed for consistency with the official templates?

**Comment by egoist** [comment]
@jazoom `v4.1.4` fixed this issue, `sass` `scss` `less` `stylus` are now available now and with css extracting support.

**Comment by jazoom** [comment]
You're smashing it, thanks.
