### ISSUE TITLE
How to add webpack.providePlugin to load jQuery?

### ISSUE THREAD

**Issue by layanto** [egoist/vbuild#58]
How do I use mergeConfig option to add the following for loading jQuery globally?

plugins = [
    new webpack.providePlugin({
        jQuery: "jquery",
        "$": "jquery",
        "window.jQuery": "jquery",
        "window.$": "jquery"
    })
]

**Comment by layanto** [comment]
Never mind. Got it to work.

**Comment by hitautodestruct** [comment]
@layanto How did you get this to work?

**Comment by egoist** [comment]
@hitautodestruct  it's common to use mergeConfig option here:

```js
module.exports = {
  mergeConfig: {
    plugins: [new webpack.ProvidePlugin()]
  }
}
```

see https://vbuild.js.org/docs/config.html#merge-webpack-config

**Comment by layanto** [comment]
This is what I have in my vue.config.js:

const webpack = require('webpack')
module.exports = {
    title: 'title here',
    resolve: true,
    mergeConfig: {
        plugins: [
            new webpack.ProvidePlugin({
                jQuery: "jquery",
                $: "jquery",
                "window.jQuery": "jquery",
                "window.$": "jquery"
            })
        ]
    }
}

Even though https://vbuild.js.org/docs/config.html#merge-webpack-config said that you can require('webpack') without installing them again in your project, I find this is not the case. I ended up having to add webpack in my project's package.json. Is this a bug?

**Comment by egoist** [comment]
@layanto which version of vbuild? It should be fixed in 3.3.0+

**Comment by layanto** [comment]
Without having webpack in my project, I get Error: Cannot find module 'webpack'

**Comment by layanto** [comment]
latest v3.4.1

**Comment by egoist** [comment]
Ok, I got this. webpack is not available in config file, only the existing loaders and `vue` do not require another install.

Sorry for this misdirection 😕 Current workaround is to install vbuild as devDependency, and `yarn add vbuild --dev` could be fast!

**Comment by layanto** [comment]
Any way to work around this? I think I like about vbuild is to not have all these build dependencies (webpack, babel, etc) as part of project dependencies.
Maybe combine the custom webpack config with vbuild config into a new 'built' config and then load the 'built' config during runtime?

**Comment by egoist** [comment]
Yes, sure. working on this. I think https://github.com/floatdrop/require-from-string would suit the need?

**Comment by egoist** [comment]
Fixed in [v4.0](https://github.com/egoist/vbuild/releases/tag/v4.0.0)

**Comment by layanto** [comment]
Thanks. Will try v4.0 today.
Found one small typo/inconsistency in lib/index.js line 16
```
const requireWithContent = require('./require-with-context')
```

**Comment by egoist** [comment]
@neves what do you mean? you don't need to use require-from-string, vbuild reads the content of config file and use require-from-string to `require` it.
