### ISSUE TITLE
Can't use less

### ISSUE THREAD

**Issue by YerkoPalma** [egoist/vbuild#6]
I'm trying to use vbuild and I have my stylesheets with less, but I'm getting this error

![screenshot from 2016-05-30 17 50 52](https://cloud.githubusercontent.com/assets/5105812/15636252/1ef06496-25cf-11e6-8404-c38fedf56616.png)

As you can see, I'm trying to import normalize. I've use Vue with less before with browserify and it works perfect, but I've never used webpack before. I'm including my styles in my main vue file like this

```vue
<style lang="less" src="./style/main.less"></style>
```
I try to add some webpack loaders for less and for sourcemap but the error is still there. Is there something I'm missing? Here is my `vbuils.js` file if it helps

```js
import path from 'path'
import ExtractTextPlugin from 'extract-text-webpack-plugin'

export default {
  // ...
  postcss: ['postcss-import'],
  webpack(config, options) {
    config.resolve.devtool = 'source-map'
    addLess(config)
    config.resolve.plugins = [ new ExtractTextPlugin('styles.css') ]
    setAlias(config)
  }
}

function cwd(...args) {
  return path.join(process.cwd(), ...args)
}

function setAlias(config) {
  config.resolve.alias = {
    components: cwd('src/components'),
    utils: cwd('src/utils'),
    helpers: cwd('src/helpers')
  }
}

function addLess(config) {
  config.resolve.module = {
    loaders: [
      {
        test: /\.less$/,
        loader: ExtractTextPlugin.extract(
          // activate source maps via loader query
          'css?sourceMap!' +
          'less?sourceMap'
        )
      }
    ]
  }
}
```

**Comment by egoist** [comment]
Simply use such `vbuild.js`:

```js
export default {
  postcss: [require('postcss-import')]
}
```

You'd better not use `ExtractTextPlugin` since it does not support hot reloading.

**Comment by egoist** [comment]
If you want to add a new loader for a section in .vue file:

```js
export default {
  webpack(config) {
    config.vue.loaders.less = ExtractTextPlugin.extract(
      'css?sourceMap!' +
      'less?sourceMap'
    )
  }
}
```
