### ISSUE TITLE
Build without tty fails since the addition of display-stats

### ISSUE THREAD

**Issue by marvinroger** [egoist/vbuild#61]
It seems `process.stdout.clearLine` is undefined when the build step is used on a CI without tty, causing the build to fail (see [this build for example](https://app.wercker.com/uniontech-thegame/uniontech-thegame.github.io/runs/build/58356138f48064010073e1e2?step=5835613c30a11f0001f0c3d8)).

**Comment by egoist** [comment]
Maybe use `if (!process.stdout.isTTY) return` to skip this plugin

**Comment by marvinroger** [comment]
Yes, that would be a good idea. Or maybe [readline.clearLine might not throw an exception](https://nodejs.org/api/readline.html#readline_readline_clearline_stream_dir).

**Comment by egoist** [comment]
Fixed in `v4.1.0`
