### ISSUE TITLE
add <script> to template

### ISSUE THREAD

**Issue by aeosynth** [egoist/vbuild#63]
i added a script tag to `App.vue`; hot reloading fails with:

    Root or manually mounted instance modified. Full reload required.

could we have an example where we can immediately test out hot reloading?

**Comment by egoist** [comment]
If you wanna test hmr, simply modify contents inside `template` tag?

**Comment by aeosynth** [comment]
yes, hot reloading works, except for `script` tags in `App.vue`. i suppose this is a question of scope; showing how to import components would help new vue users, but it's not necessary for a build tool.

**Comment by egoist** [comment]
Thanks for the suggestion, I'll improve the template later ;)
