### ISSUE TITLE
Option for which port to use for dev server

### ISSUE THREAD

**Issue by jazoom** [egoist/vbuild#65]
It is annoying to have to say "yes" every time I load up the dev server. In my setup port 4000 is always taken. I just would like to specify which port vbuild uses for the dev server.

**Comment by egoist** [comment]
There's a `port` option for this.

**Comment by jazoom** [comment]
I'd say so. I've read through the whole documentation 3 times.

**Comment by egoist** [comment]
Sorry for the inconvenience 😆

**Comment by jazoom** [comment]
No probs. Thanks for the great project. I hated having all that clutter in my project's dependencies and extra config files everywhere.
