### ISSUE TITLE
Browser gets closed when exiting the dev server

### ISSUE THREAD

**Issue by jazoom** [egoist/vbuild#67]
Even if there are 20 tabs open, when the dev server is exited from the command line the browser gets closed. Happening on Chrome on Linux. `open: true` in config.

**Comment by egoist** [comment]
Does it always perform like this?

**Comment by jazoom** [comment]
It has been.

**Comment by layanto** [comment]
Doesn't close browser on mine.

**Comment by jazoom** [comment]
Yeah, mine hasn't either today. Weird.

**Comment by egoist** [comment]
reopen the issue if this happens again

**Comment by jazoom** [comment]
Actually, It has happened several more times. I don't know what causes it, but once it has happened, it keeps happening until reboot.

**Comment by egoist** [comment]
Do you still have this problem with v6?

**Comment by jazoom** [comment]
I actually ended up turning off the auto-open of the browser and I haven't had the problem since, so I don't know if the issue has persisted.

**Comment by egoist** [comment]
@jazoom thanks, closing for now
