### ISSUE TITLE
Cannot find element: #app with the default init project

### ISSUE THREAD

**Issue by ryanmclaughlin** [egoist/vbuild#68]
Hi there, I'm getting this with the default project after running `vbuild init my-project` and `npm run dev`

`[Vue warn]: Cannot find element: #app`

**Comment by egoist** [comment]
Reinstall vbuild to `v4.1.6` should fix this.

**Comment by ryanmclaughlin** [comment]
@egoist Thanks. Is there an index.html anywhere? Wondering how where I can add stuff in the `<head>`.

**Comment by egoist** [comment]
Check out https://vbuild.js.org/docs/templates.html

The short answer, use `template` option to set custom index.html template. You can use the default template and add your stuffs. https://github.com/egoist/vbuild/blob/master/lib/template.html

```js
export default {
  template: './my-template.html'
}
```

**Comment by ryanmclaughlin** [comment]
Thanks much @egoist. Super helpful.
