### ISSUE TITLE
How to run eslint on its own independent of building production?

### ISSUE THREAD

**Issue by layanto** [egoist/vbuild#70]
Is it possible to run eslint on its own to check code in src without being part of vbuild prod?

**Comment by egoist** [comment]
Yeah, but it's out of the scope of vbuild.

```bash
$ eslint ./src/** --ext .vue --ext .js
```

Add add `eslint-config-vue` to your `.eslintrc` or anywhere `eslint` can read.

**Comment by layanto** [comment]
But then I will need to add eslint as a dependency to my project when it already is a dependency of vbuild.
I thought since vbuild already does eslint but only when building, maybe can add feature to do eslint on its own with vbuild like vbuild --eslint

**Comment by egoist** [comment]
I will consider this, since it doesn't run webpack at all so it might be `vbuild eslint` instead. And it can simply spawn `node_modules/.bin/eslint` in a child process with some default options.

So PR welcome ;)

**Comment by layanto** [comment]
Wanted to give this a go but not sure where to start. I also tried overriding the indent rule to 4 spaces via .eslintrc below but eslint appeared to still expect 2 spaces for indent as per eslint-config-vue

```
{
  "extends": "vue",
  "rules": {
    "indent": ["error", 4]
  }
}
```

**Comment by egoist** [comment]
First you need to set `eslint` in `vue.config.js`:

```js
export default {
  eslint: {
    configFile: '/path/to/.eslintrc'
  }
}
```

**Comment by egoist** [comment]
Closed since this is not going to happen in the near future.
