### ISSUE TITLE
Dist option seems flaky.

### ISSUE THREAD

**Issue by qur2** [egoist/vbuild#72]
Changing the dist target does not work. In my `vbuild` config, I set the `dist` option to something like:
```
dist: path.join(__dirname, 'dist', 'sub-folder'),
```

Then, the html index file that is generated has a hardcoded payload like this:
```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"statusCode":404,"error":"Not Found"}</pre></body></html>
```

Any hint? I'm looking at that and will report back any finding I make.

**Comment by egoist** [comment]
eh that works for me, can you provide a repo for repro?

**Comment by qur2** [comment]
Hi,

I don't have a repo at hand (the problematic stuff is company material). However, I found that the file is there, it's just that there is this "empty" index file in `dist/`. in `dist/sub-folder`, I find the index I expect. Then, it's a matter of configuring the `publicPath` correctly.

So if the root `index.html` is fine for you, I suppose this issue can be closed. Sorry for the noise and thanks for your fast response. Also thanks for your good work, keep it up!

**Comment by egoist** [comment]
that makes sense ;)
