### ISSUE TITLE
Exclude vue and vue-template-compiler from vbuild

### ISSUE THREAD

**Issue by egoist** [egoist/vbuild#73]
because it sometimes raises a `vue-template-compiler version mismatches` issue.

**Comment by throrin19** [comment]
I have the same error

**Comment by egoist** [comment]
@throrin19 try installing vue and vue-template-compiler in your project

**Comment by egoist** [comment]
um... I'm going to exclude these two deps 😅

**Comment by egoist** [comment]
It looks vue-loader can only resolve vue-template-compiler which is in vbuild's node_modules

If we exclude vue-template-compiler then we need to exclude vue-loader and vue-style-loader 😱

I think removing vue-template-compiler and only install expected vue version (2.1.3) in your project could solve this for now.

**Comment by throrin19** [comment]
I found the problem : To works we should install the latest version of `vue-loader` directly in the project

**Comment by egoist** [comment]
that's what I wanna prevent, no (or less) dev dependencies in your project

**Comment by throrin19** [comment]
But, If we should update vue version or other component (vue-router, vuex, ...), we will have to wait for you to publish an update.

**Comment by egoist** [comment]
This is my solution to it https://github.com/egoist/vbuild/commit/cf007fb9a11a5299efebc9c604334510777af96b

**Comment by throrin19** [comment]
And I think it was a problem with Yarn.

Whith this package.json : 

```
"dependencies": {
    "vue": "2.1.5",
    "vue-material": "0.4.1",
    "vue-touch-ripple": "2.2.2"
  },
  "devDependencies": {
    "babel-core": "^6.20.0",
    "babel-eslint": "7.1.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-2": "^6.18.0",
    "node-sass": "4.0.0",
    "sass-loader": "4.0.2",
    "vbuild": "4.2.2",
    "vue-loader": "10.0.2",
    "vue-template-compiler": "2.1.5"
  }
```

If I run the installation with `npm install` I have no problem, the compilation works fine.
If I run the installation with `yarn` I have the problem between vue@2.1.5 and vue-template-compiler@2.1.3.

After tests, the problem is the dependances resolutions if I install vbuild locally to the project. (I make that to simplify co-workers production envs). Any idea ?

**Comment by egoist** [comment]
Yep, my commit would fix this.

**Comment by throrin19** [comment]
Ok :). I'll wait for the release of this fix

**Comment by egoist** [comment]
Update to `4.3.0` should be good!

**Comment by throrin19** [comment]
It works fine thanks :)

**Comment by layanto** [comment]
vbuild v4.3.1 onwards exclude vue-loader and vue-template-compiler. Are we expected to include them as devDependencies in the project now?

**Comment by egoist** [comment]
@layanto yes
