### ISSUE TITLE
Install Failed Using Yarn

### ISSUE THREAD

**Issue by maxapps** [egoist/vbuild#74]
The installation was successful using npm but failed when I attempted to use yarn (prior to installing via npm).

System is Windows 10, Node version 6.9.2. The error generated was:
> error An unexpected error occurred: "ENOENT: no such file or directory, open 'C:\\Users\\{me}\\AppData\\Local\\Yarn\\config\\global\\node_modules\\@sindresorhus\\df\\index.js'".

This was the first time I've ever (attempted) to use yarn but the command was entered exactly asd listed in the vbuild docs (i.e. `yarn global add vbuild`).

Otherwise, I'm looking forward to checking out this great looking Vue tool.

**Comment by egoist** [comment]
`v4.2.1` should just work
