### ISSUE TITLE
unmet peer dependency

### ISSUE THREAD

**Issue by codeofsumit** [egoist/vbuild#78]
hey there,

I'm still trying to make vbuild the go-to stop for vue apps in our team but I'm still struggling to set this up so new devs can easily get started. The following scenario:

I want to add a CSS library that includes sass after I `vbuild init`ed my project.

These are the steps I currently have to do:

1. `npm install css-lib --save` => errors because of missing sass-loader
2. `npm install sass-loader --save-dev`
Errors: 
```
UNMET PEER DEPENDENCY node-sass@^3.4.2
UNMET PEER DEPENDENCY webpack@^1.12.6 || ^2.1.0-beta
```

3. `npm install node-sass --save-dev`
4. Find out which version of webpack vbuild uses, and install it (even though vbuild "comes with webpack"?) This is confusing me a bit as I struggle to understand how webpack is abstracted away here. `npm install webpack@^2.1.0-beta`.

Then it works with a couple remaining warnings about unmet peer deps of node-sass (different versions).

Is there any way to make this a bit more straightforward?

**Comment by egoist** [comment]
> These are the steps I currently have to do:

I think you do need to follow these steps in a typical vue-webpack project too? 

> Find out which version of webpack vbuild uses, and install it

Install webpack in your project does not make any sense except for disabling the `unmet peerDependency error`, try installing vbuild in your project instead

> a bit more straightforward

um, I don't know what's the pain point for you, after did all these steps you listed above I think other devs can just come and enjoy it? no?

**Comment by codeofsumit** [comment]
thanks for the clarification.

> Install webpack in your project does not make any sense except for disabling the unmet peerDependency error

But isn't this necessary as of npm 3? It's an actual error, not a warning.

> um, I don't know what's the pain point for you, after did all these steps you listed above I think other devs can just come and enjoy it? no?

yea you're right. At first I thought vbuild should deliver all those things out of the box but I guess it makes much more sense for me to customize for our team and provide a boilerplate repo for the team.
