### ISSUE TITLE
Dev server opens at 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by jazoom** [egoist/vbuild#79]

**Comment by egoist** [comment]
you can still visit it via localhost, what's the trouble?

**Comment by jazoom** [comment]
Then why make it 0.0.0.0? Just to be different? Or is the a technical advantage to it I'm not aware of.

It was only a minor trouble since I had to go and update the CORS rules in my servers that my web app connects to.

**Comment by jazoom** [comment]
How do I make the tab automatically open to localhost instead of 0.0.0.0?

**Comment by egoist** [comment]
because listen on 0.0.0.0 so that you can visit the website via other devices if they connected to the same network, you can change this via `--host localhost`

**Comment by jazoom** [comment]
Okay, thanks. It seems all the docs need to be changed since they still all say default is "localhost".

**Comment by egoist** [comment]
I will update the output url to `localhost` then, much easier than updating docs 😂

**Comment by egoist** [comment]
Fixed in `v4.3.2`.

<img width="828" alt="2016-12-16 2 52 50" src="https://cloud.githubusercontent.com/assets/8784712/21254306/6cd0c17e-c39f-11e6-95b3-4089e3cec195.png">
