### ISSUE TITLE
Usage of vendor

### ISSUE THREAD

**Issue by throrin19** [egoist/vbuild#83]
Hi,
I have another question about vbuild. How can I create my file vendor.js and manifest.js to group all I have in node_module?

Thanks

**Comment by egoist** [comment]
Check out the vendor option: https://vbuild.js.org/docs/config.html#shared-options

```js
module.exports = {
  vendor: ['vue', 'vuex']
}
```

**Comment by throrin19** [comment]
But if I can group all vendors dependencies ? (all dependencies in the npm_module folder, not only vue and vuex) ?

**Comment by egoist** [comment]
`Object.keys(require('./package').dependencies)`
