### ISSUE TITLE
Use rollup ?

### ISSUE THREAD

**Issue by throrin19** [egoist/vbuild#84]
It's possible to use rollup instead of uglify ?

**Comment by egoist** [comment]
what do you mean? how's uglify related rollup here?

**Comment by throrin19** [comment]
Sorry I make a mistakes. It's possible to just use rollup in vbuild to bundle the app ?

**Comment by egoist** [comment]
You can try rollup-loader with `<script lang="rollup"></script>`, but I never tested this.

**Comment by throrin19** [comment]
Thanks. Otherwise, is it possible to do tree-shaking in vbuild or is some-shose of similar is done basic?

Sorry for my question but I search to remove all unued code and I don't know if it's make basically (I'm noob with webpack)

**Comment by egoist** [comment]
Webpack 2 natively support tree-shaking (only if you use `ES6 modules`).

**Comment by throrin19** [comment]
Thanks :)

**Comment by zephraph** [comment]
Can we close?

**Comment by throrin19** [comment]
Yes 😊Le 28 janv. 2017 8:49 PM, Zephraph <notifications@github.com> a écrit :Can we close?
