### ISSUE TITLE
Ideas!

### ISSUE THREAD

**Issue by yyx990803** [egoist/vbuild#9]
Hi there,

I tried `vbuild` out and really liked it. This kind of "no config just build" experience is really cool. I remember seeing a suggestion somewhere of pulling this into `vuejs` organization, but there are some ideas I want to discuss.

The way it works currently has overlapping functionality with `vue-cli`. The difference is the tradeoff between user experience and configurability. `vbuild` is very very nice for quick prototyping, however in production, almost every user will have different needs, so a pre-configured build tool has limited flexibility in production use.

My hope is that we can fold `vbuild` into `vue-cli` as a new command: `vue build`, and give it a more clearly defined goal: making prototyping Vue apps super super easy. So:
- if a user wants to build a production app, use `vue init`;
- if a user wants to quickly prototype an idea, use `vue build --dev` (and in most cases can later just copy the `src` files into a production scaffold generated with `vue init`)

By focusing on prototyping we can worry less about production problems, and provide more user experience improvements:
- use a lighter weight ES2015 transpiler e.g. `buble`
- support directly building a `*.vue` file, e.g. `vue build App.vue` and boom
- auto-infer the npm dependencies in the files and `npm install` them automatically

If you are interested in this idea, I'd love to have you join the team and work on this feature. What do you think?

**Comment by egoist** [comment]
Wow, that's actually what `vue build` is supposed to be, I'm very interested in this.

**Comment by zephraph** [comment]
I think `vbuild`, and potentially by extension `vue build`, have greater utility than being a quick prototyping tool. One of the things I explicitly _don't_ like about `create-react-app` is that it gives no possibility of configuration whatsoever. `vbuild` on the other hand gives sane defaults that can actually be used to build a production app, but also gives the user the ability to modify the underlying configuration slightly to suit their needs.

**Comment by zephraph** [comment]
I believe this can now be closed. ^_^
