### ISSUE TITLE
devServer example

### ISSUE THREAD

**Issue by zigomir** [egoist/vbuild#93]
Trying to get it working with `devServer` with no luck. Looking at [webpack docs](https://webpack.js.org/configuration/dev-server/#devserver-proxy) says it takes object, but `vbuild` [development options](https://vbuild.js.org/docs/config.html#development-options) says it takes a function.

Is this even same `devServer`?

I can't to get it working just yet, do you maybe have an example?

**Comment by egoist** [comment]
devServer there is provided by webpack-dev-server but we're using a custom server 😅 this one here is just a function that takes `express()` instance as argument

**Comment by egoist** [comment]
maybe we should switch to that 🤔

**Comment by zigomir** [comment]
I see you included this in [vue-cli build](https://github.com/vuejs/vue-cli/pull/287) - neat-o!
