### ISSUE TITLE
v5 breaking on "extract-text-webpack-plugin"

### ISSUE THREAD

**Issue by marvinroger** [egoist/vbuild#94]
greenkeeper just notified me the v5 was breaking my build.

See, for the same code:

* With v4: https://travis-ci.org/INTECH-RGBH/homie-dashboard/jobs/188885694#L400
* With v5:  https://travis-ci.org/INTECH-RGBH/homie-dashboard/jobs/189207153#L404

It only fails with `vbuild` production releases. `vbuild --dev` builds correctly

**Comment by egoist** [comment]
webpack 2 rc.3 introduces performance check, some of your bundles are way too big:

```bash
This can impact web performance.
Assets: 
  static/fontawesome-webfont.svg (444 kB)
  client.90bc0cc4.js (1.79 MB)
```

Check out https://webpack.js.org/configuration/performance/ for this

Currently you can disable it by: 

```js
export default {
  mergeConfig: {
    performance: {hints: false}
  }
}
```

**Comment by marvinroger** [comment]
I was not expecting a *warning* to actually exit with a non-0 status code. Anyway it works now, thanks!

**Comment by marvinroger** [comment]
@egoist the `client.js` is way too big, indeed. After checking out the content of the file (built for production with `vbuild`, I see `process.env.NODE_ENV` is not replaced, so the bundle is not optimized. Although it works with the template. I have no idea what's going on.

**Comment by egoist** [comment]
ah weird, no doubt it's set correctly https://github.com/egoist/vbuild/blob/master/lib/webpack/config.prod.js#L11

**Comment by marvinroger** [comment]
I know, it's weird.

If you want to see it by yourself:

```bash
git clone https://github.com/INTECH-RGBH/homie-dashboard.git \
  && cd homie-dashboard \
  && git checkout e3225f9a7607f76e863946fdc7d64a31b98cb4f5 \
  && yarn \
  && yarn app-build
```

(this is a pretty big project, so it'll take some time)

Then see the `client-*.js` file, you'll see it contains some `process.env.NODE_ENV`.

**Comment by egoist** [comment]
I use `sao INTECH-RGBH/homie-dashboard foo --install` to download it, will be faster than git clone 😎

**Comment by egoist** [comment]
<img width="1072" alt="2017-01-09 9 01 24" src="https://cloud.githubusercontent.com/assets/8784712/21767382/d1da2124-d6ae-11e6-9114-fea1d64213c1.png">

seems the vue-grid-layout contains inline sourcemaps, I don't know why webpack didn't remove it

**Comment by egoist** [comment]
<img width="653" alt="2017-01-09 9 16 16" src="https://cloud.githubusercontent.com/assets/8784712/21767767/e2df3ed0-d6b0-11e6-8839-f66bb449df19.png">

why vue-grid-layout contains the `eval` thing 😂

**Comment by egoist** [comment]
I think they had to change the `devtool` for umd build https://github.com/jbaysolutions/vue-grid-layout/blob/master/webpack.config.js#L57

**Comment by marvinroger** [comment]
Oh, awesome, thanks for the finding! What tool did you use to generate the tree? Might be helpful to avoid this kind of non-related-to-vbuild issues. 😒

**Comment by egoist** [comment]
https://github.com/th0r/webpack-bundle-analyzer
