### ISSUE TITLE
Cordova / Phonegap Support?

### ISSUE THREAD

**Issue by boustanihani** [egoist/vbuild#97]
Will there be any Cordova / Phonegap support?

The ability to build an Android / iOS package would be great :)

**Comment by egoist** [comment]
hmm, I don't what changes are required to be made for this, any suggestions?

**Comment by Rob-pw** [comment]
I have to attempt this myself, so I'll let you know -- if there's any advice you could give, that'd be ace. https://github.com/markmarijnissen/webpack-cordova-plugin

**Comment by egoist** [comment]
@Rob-pw this plugin looks nice and really simple to work with vbuild, so I'm closing this.
